# Numpy Assignments

<div class = "alert alert-block alert-info"
    <b>1. Write a NumPy program to get the numpy version and show numpy build configuration.</b>
</div>   

In [1]:
import numpy as np

In [5]:
np. __version__

'1.24.4'

In [6]:
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

<div class = "alert alert-block alert-info"
    <b>2. Write a NumPy program to get help on the add function.</b>
</div>   

In [16]:
a1 = np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[2,8],[4,6],[8,5]])
print(f"Array 1 : \n {a1}")
print(f"Array 2 : \n {a2}")
print(f"Apply Add Function to a1 and a2 : \n {np.add(a1,a2)}")

Array 1 : 
 [[1 2]
 [3 4]
 [5 6]]
Array 2 : 
 [[2 8]
 [4 6]
 [8 5]]
Apply Add Function to a1 and a2 : 
 [[ 3 10]
 [ 7 10]
 [13 11]]


<div class = "alert alert-block alert-info"
    <b>3. Write a NumPy program to test whether none of the elements of a given array is zero.</b>
</div>   

In [19]:
x2 = np.array([0, 2, 3, 4])
print(x2.all())   # gives false if any one element is zero

False


<div class = "alert alert-block alert-info"
    <b>4. Write a NumPy program to test whether any of the elements of a given array is non-zero.</b>
</div>   

In [20]:
x1 = np.array([1, 2, 3, 4])
print(x1.all())   # gives true if all are non-zero

True


<div class = "alert alert-block alert-info"
    <b>5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).</b>
</div>   

In [23]:
arr1 = np.array([1, 0, np.nan, np.inf])    # not a number or not infinity
print(f"Original array: {arr1}\n")

print(f"Test a given array element-wise for finiteness: {np.isfinite(arr1)}")

Original array: [ 1.  0. nan inf]

Test a given array element-wise for finiteness: [ True  True False False]


<div class = "alert alert-block alert-info"
    <b>6. Write a NumPy program to test element-wise for positive or negative infinity.</b>
</div>   

In [26]:
arr2 = np.array([1, 0, -np.inf, np.inf]) 
print(f"Original array: {arr2}\n")

print(f"To test element-wise for positive infinity: {np.isposinf(arr2)}\n")    # for positive infinity find
print(f"To test element-wise for negative infinity: {np.isneginf(arr2)}\n")    # for negative infinity find

Original array: [  1.   0. -inf  inf]

To test element-wise for positive infinity: [False False False  True]

To test element-wise for negative infinity: [False False  True False]



<div class = "alert alert-block alert-info"
    <b>7. Write a NumPy program to test element-wise for NaN of a given array.</b>
</div>   

In [39]:
arr3 = np.array([1, 0, np.nan, 4])   
print(f"Original array: {arr3}\n")

print(f"To test element-wise for NaN: {np.isnan(arr3)}\n")    # for test nan by element-wise

Original array: [ 1.  0. nan  4.]

To test element-wise for NaN: [False False  True False]



<div class = "alert alert-block alert-info"
    <b>8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also
test whether a given number is a scalar type or not.</b>
</div>   

In [30]:
arr4 = np.array([1+2j, 2+0j, 4.5, 3, 4, 2j, 4j])
print(f"Original array: {arr4}\n")

print(f"To test element-wise for complex: {np.iscomplex(arr4)}\n")    # for test complex num
print(f"To test element-wise for real: {np.isreal(arr4)}\n")    # for test real num
print(f"To test element for scalar: {np.isscalar(3.4)}\n")    # for test complex num

Original array: [1. +2.j 2. +0.j 4.5+0.j 3. +0.j 4. +0.j 0. +2.j 0. +4.j]

To test element-wise for complex: [ True False False False False  True  True]

To test element-wise for real: [False  True  True  True  True False False]

To test element for scalar: True



<div class = "alert alert-block alert-info"
    <b>9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.</b>
</div>   

In [37]:
x = np.array([1, 5])
y = np.array([2, 5])
print(f"Original array x: {x}\n")
print(f"Original array y: {y}\n")

print(f"To test Greater: {np.greater(x,y)}\n")
print(f"To test Greater Or Equal : {np.greater_equal(x,y)}\n")

print(f"To test lesser: {np.less(x,y)}\n")
print(f"To test lesser Or Equal : {np.less_equal(x,y)}\n")

Original array x: [1 5]

Original array y: [2 5]

To test Greater: [False False]

To test Greater Or Equal : [False  True]

To test lesser: [ True False]

To test lesser Or Equal : [ True  True]



<div class = "alert alert-block alert-info"
    <b>10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the
memory occupied by the array.</b>
</div>   

In [43]:
b1 = np.array([1, 7, 13, 105])
print(f"Original array b1: {b1}\n")

print(f"Determine the size of the memory occupied by the array: {b1.size * b1.itemsize}")

Original array b1: [  1   7  13 105]

Determine the size of the memory occupied by the array: 16


In [ ]:
<div class = "alert alert-block alert-info"
    <b>11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.</b>
</div>   