<center><b><h1>Assignment_1_Numpy</h1></b></center>

<div class = "alert alert-block alert-info"
    <b>1. Write a NumPy program to get the numpy version and show numpy build configuration.</b>
</div>   

In [1]:
import numpy as np

In [2]:
np. __version__

'1.24.4'

In [3]:
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

<div class = "alert alert-block alert-info"
    <b>2. Write a NumPy program to get help on the add function.</b>
</div>   

In [4]:
a1 = np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[2,8],[4,6],[8,5]])
print(f"Array 1 : \n {a1}")
print(f"Array 2 : \n {a2}")
print(f"Apply Add Function to a1 and a2 : \n {np.add(a1,a2)}")

Array 1 : 
 [[1 2]
 [3 4]
 [5 6]]
Array 2 : 
 [[2 8]
 [4 6]
 [8 5]]
Apply Add Function to a1 and a2 : 
 [[ 3 10]
 [ 7 10]
 [13 11]]


<div class = "alert alert-block alert-info"
    <b>3. Write a NumPy program to test whether none of the elements of a given array is zero.</b>
</div>   

In [5]:
x2 = np.array([0, 2, 3, 4])
print(x2.all())   # gives false if any one element is zero

False


<div class = "alert alert-block alert-info"
    <b>4. Write a NumPy program to test whether any of the elements of a given array is non-zero.</b>
</div>   

In [6]:
x1 = np.array([1, 2, 3, 4])
print(x1.all())   # gives true if all are non-zero

True


<div class = "alert alert-block alert-info"
    <b>5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).</b>
</div>   

In [7]:
arr1 = np.array([1, 0, np.nan, np.inf])    # not a number or not infinity
print(f"Original array: {arr1}\n")

print(f"Test a given array element-wise for finiteness: {np.isfinite(arr1)}")

Original array: [ 1.  0. nan inf]

Test a given array element-wise for finiteness: [ True  True False False]


<div class = "alert alert-block alert-info"
    <b>6. Write a NumPy program to test element-wise for positive or negative infinity.</b>
</div>   

In [8]:
arr2 = np.array([1, 0, -np.inf, np.inf]) 
print(f"Original array: {arr2}\n")

print(f"To test element-wise for positive infinity: {np.isposinf(arr2)}\n")    # for positive infinity find
print(f"To test element-wise for negative infinity: {np.isneginf(arr2)}\n")    # for negative infinity find

Original array: [  1.   0. -inf  inf]

To test element-wise for positive infinity: [False False False  True]

To test element-wise for negative infinity: [False False  True False]



<div class = "alert alert-block alert-info"
    <b>7. Write a NumPy program to test element-wise for NaN of a given array.</b>
</div>   

In [9]:
arr3 = np.array([1, 0, np.nan, 4])   
print(f"Original array: {arr3}\n")

print(f"To test element-wise for NaN: {np.isnan(arr3)}\n")    # for test nan by element-wise

Original array: [ 1.  0. nan  4.]

To test element-wise for NaN: [False False  True False]



<div class = "alert alert-block alert-info"
    <b>8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also
test whether a given number is a scalar type or not.</b>
</div>   

In [10]:
arr4 = np.array([1+2j, 2+0j, 4.5, 3, 4, 2j, 4j])
print(f"Original array: {arr4}\n")

print(f"To test element-wise for complex: {np.iscomplex(arr4)}\n")    # for test complex num
print(f"To test element-wise for real: {np.isreal(arr4)}\n")    # for test real num
print(f"To test element for scalar: {np.isscalar(3.4)}\n")    # for test complex num

Original array: [1. +2.j 2. +0.j 4.5+0.j 3. +0.j 4. +0.j 0. +2.j 0. +4.j]

To test element-wise for complex: [ True False False False False  True  True]

To test element-wise for real: [False  True  True  True  True False False]

To test element for scalar: True



<div class = "alert alert-block alert-info"
    <b>9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
less_equal) of two given arrays.</b>
</div>   

In [11]:
x = np.array([1, 5])
y = np.array([2, 5])
print(f"Original array x: {x}\n")
print(f"Original array y: {y}\n")

print(f"To test Greater: {np.greater(x,y)}\n")
print(f"To test Greater Or Equal : {np.greater_equal(x,y)}\n")

print(f"To test lesser: {np.less(x,y)}\n")
print(f"To test lesser Or Equal : {np.less_equal(x,y)}\n")

Original array x: [1 5]

Original array y: [2 5]

To test Greater: [False False]

To test Greater Or Equal : [False  True]

To test lesser: [ True False]

To test lesser Or Equal : [ True  True]



<div class = "alert alert-block alert-info"
    <b>10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the
memory occupied by the array.</b>
</div>   

In [12]:
b1 = np.array([1, 7, 13, 105])
print(f"Original array b1: {b1}\n")

print(f"Determine the size of the memory occupied by the array: {b1.size * b1.itemsize}")

Original array b1: [  1   7  13 105]

Determine the size of the memory occupied by the array: 16


<div class = "alert alert-block alert-info"
    <b>11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.</b>
</div>   

In [13]:
print(f"To create an array of 10 zeros: {np.zeros(10)}\n")

print(f"To create an array of 10 zeros: {np.ones(10,dtype=int)} \n")

print(f"To create an array of 10 zeros: {np.ones(10,int)*5} \n")

To create an array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

To create an array of 10 zeros: [1 1 1 1 1 1 1 1 1 1] 

To create an array of 10 zeros: [5 5 5 5 5 5 5 5 5 5] 



<div class = "alert alert-block alert-info"
    <b>12. Write a NumPy program to create an array of the integers from 30 to70.</b>
</div>   

In [14]:
arr1 = np.arange(30,171)
print(arr1)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170]


<div class = "alert alert-block alert-info"
    <b>13. Write a NumPy program to create an array of all the even integers from 30 to 70.</b>
</div>   

In [15]:
arr2 = np.arange(30,70,2)
print(arr2)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


<div class = "alert alert-block alert-info"
    <b>14. Write a NumPy program to create a 3x3 identity matrix.</b>
</div>   

In [16]:
arr3 = np.eye(3,3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<div class = "alert alert-block alert-info"
    <b>15. Write a NumPy program to generate a random number between 0 and 1.</b>
</div>   

In [17]:
arr4 = np.random.rand(4)  # 4 is how many random number you want btn 0 and 1
print(arr4)

[0.41498892 0.64841336 0.53652153 0.01521831]


<div class = "alert alert-block alert-info"
    <b>16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.</b>
</div>   

In [18]:
arr5 = np.random.randn(15)
print(arr5)

[ 1.06185897 -0.3497823   1.56040166  0.81863032 -0.72819445  1.6979369
  0.96683292  2.336639   -0.97609707  0.98122587  0.74125654 -0.59905206
  2.03642491  0.31509342 -0.35656076]


<div class = "alert alert-block alert-info"
    <b>17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.</b>
</div>   

In [19]:
arr6 = np.arange(15,55)
print(f"Original array :\n {arr6} \n")

print(f"All values except the first and last of the said vector:\n {arr6[1:-1]}")

Original array :
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54] 

All values except the first and last of the said vector:
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


<div class = "alert alert-block alert-info"
    <b>18. Write a NumPy program to create a 3X4 array.</b>
</div>   

In [20]:
arr7 = np.array([[1,2,3,4],[5,6,7,8],[2,8,3,9]])

print(f"Original array :\n {arr7} \n")

Original array :
 [[1 2 3 4]
 [5 6 7 8]
 [2 8 3 9]] 



<div class = "alert alert-block alert-info"
    <b>19. Write a NumPy program to create a vector of length 10 with values evenly distributed
between 5 and 50.</b>
</div>   

In [21]:
arr8 = np.random.randint(5,50,10)
print(f"A vector of length 10 with values evenly distributed between 5 and 50 :\n {arr8} \n")

A vector of length 10 with values evenly distributed between 5 and 50 :
 [19 18 43 45 33 39 23 45 33 27] 



<div class = "alert alert-block alert-info"
    <b>20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
numbers in the range from 9 to 15.</b>
</div>   

In [22]:
x = np.arange(21)
print(f"Original array :\n {x} \n")

x[(x >= 9) & (x <= 15)] *= -1

print(f"change the sign of the numbers in the range from 9 to 15 :\n {x}")

Original array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

change the sign of the numbers in the range from 9 to 15 :
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


<div class = "alert alert-block alert-info"
    <b>21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.</b>
</div>   

In [23]:
x1 = np.random.randint(0,11,5)
print(f"Original array :\n {x1} \n")

Original array :
 [4 3 1 5 9] 



<div class = "alert alert-block alert-info"
    <b>22. Write a NumPy program to multiply the values of two given vectors.</b>
</div>   

In [24]:
w1 = np.array([[1,2],[3,4],[5,6]])
w2 = np.array([[6,7],[3,2],[4,6]])

print(f"To multiply the values of two given vectors :\n{w1*w2} ")

To multiply the values of two given vectors :
[[ 6 14]
 [ 9  8]
 [20 36]] 


<div class = "alert alert-block alert-info"
    <b>23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.</b>
</div>   

In [25]:
x1 = np.arange(10, 22).reshape((3, 4))
print(x1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


<div class = "alert alert-block alert-info"
    <b>24. Write a NumPy program to find the number of rows and columns of a given matrix.</b>
</div>   

In [26]:
x1.shape

(3, 4)

<div class = "alert alert-block alert-info"
    <b>25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.</b>
</div>   

In [27]:
x2 = np.eye(3,dtype=int)
print(x2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


<div class = "alert alert-block alert-info"
    <b>26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
equal to 1, and inside 0.</b>
</div>   

In [28]:
x1 = np.zeros((10,10),dtype=int)
print(f"Original array :\n{x1} \n")

x1[0]=1
x1[-1]=1
x1[:,0]=1
x1[:,-1]=1
print(f"\nThe borders will be equal to 1, and inside 0:\n{x1}")

Original array :
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 


The borders will be equal to 1, and inside 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


<div class = "alert alert-block alert-info"
    <b>27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.</b>
</div>   

In [29]:
x2 = np.diag([1, 2, 3, 4, 5])
print(x2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


<div class = "alert alert-block alert-info"
    <b>28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.</b>
</div>   

In [30]:
x3 = np.random.randint(1,50,size=(3,3,3))
print(f"To create a 3x3x3 array filled with arbitrary values :\n {x3}")

To create a 3x3x3 array filled with arbitrary values :
 [[[44  4 28]
  [ 9 15 28]
  [ 9 49  6]]

 [[ 5 47 23]
  [25 17 41]
  [19 28 37]]

 [[40 18 23]
  [ 2  4 31]
  [34 25 22]]]


<div class = "alert alert-block alert-info"
    <b>29. Write a NumPy program to compute the inner product of two given vectors.</b>
</div>   

In [31]:
x = np.array([4, 5])
y = np.array([7, 10])

print(np.dot(x, y))

78


<div class = "alert alert-block alert-info"
    <b>30. Write a NumPy program to sort a given array by row and column in ascending order.</b>
</div>   

In [32]:
arr1 = np.random.randint(1,10,size=(3,3))
print(f"Original array :\n {arr1} \n")

print(f"To sort a given array by row:\n{np.sort(arr1,axis=1)}\n")
print(f"To sort a given array by column:\n{np.sort(arr1,axis=0)}")

Original array :
 [[2 3 8]
 [3 1 1]
 [7 7 3]] 

To sort a given array by row:
[[2 3 8]
 [1 1 3]
 [3 7 7]]

To sort a given array by column:
[[2 1 1]
 [3 3 3]
 [7 7 8]]


<div class = "alert alert-block alert-info"
    <b>31. Write a NumPy program to extract all numbers from a given array which are less and greater
than a specified number.</b>
</div>   

In [33]:
arr2 = np.random.randint(1,10,size=(3,3))
print(f"Original array :\n {arr2} \n")

n = 6
print(f"Extract all numbers from a given array which are less:\n {arr2[arr2<n]}")

print(f"Extract all numbers from a given array which are greater:\n {arr2[arr2>n]}")

Original array :
 [[6 7 1]
 [6 7 3]
 [3 4 2]] 

Extract all numbers from a given array which are less:
 [1 3 3 4 2]
Extract all numbers from a given array which are greater:
 [7 7]


<div class = "alert alert-block alert-info"
    <b>32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
given number.</b>
</div>   

In [34]:
arr3 = np.random.randint(1,10,size=(3,3))
print(f"Original array :\n {arr3} \n")

Original array :
 [[5 3 9]
 [8 4 4]
 [6 5 5]] 



In [35]:
n = 4
re = 10

print(f"Replace 're' with if array ele is equal to n: \n {np.where(arr3 == n, re, arr3)}\n")
print(f"Replace 're' with if array ele is less to n: \n {np.where(arr3 < n, re, arr3)}\n")
print(f"Replace 're' with if array ele is greater to n: \n {np.where(arr3 > n, re, arr3)}\n")

Replace 're' with if array ele is equal to n: 
 [[ 5  3  9]
 [ 8 10 10]
 [ 6  5  5]]

Replace 're' with if array ele is less to n: 
 [[ 5 10  9]
 [ 8  4  4]
 [ 6  5  5]]

Replace 're' with if array ele is greater to n: 
 [[10  3 10]
 [10  4  4]
 [10 10 10]]



<div class = "alert alert-block alert-info"
    <b>33. Write a NumPy program to create an array of equal shape and data type of a given array.</b>
</div>   

In [36]:
x1 = np.array([[1,2],[4,5]])
x2 = np.copy(x1)

print(f"x1 shape : {x1.shape} & x1 dtype : {x1.dtype}")
print(f"x2 shape : {x2.shape} & x2 dtype : {x2.dtype}")

x1 shape : (2, 2) & x1 dtype : int32
x2 shape : (2, 2) & x2 dtype : int32


<div class = "alert alert-block alert-info"
    <b>34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a
variable.</b>
</div>   

In [37]:
nums = np.random.randint(1,50,size=(3,5,4))
print(f"Arrays:\n{nums}")

Arrays:
[[[32  1  1 29]
  [19 31  3  9]
  [16  9 30 29]
  [10 49  8  1]
  [44 23 18  4]]

 [[45 44  6 46]
  [47 16 47 20]
  [39 28 26 14]
  [45 34 14  8]
  [25 43 47 25]]

 [[15 37  1 27]
  [32 36 44 28]
  [38 40  7 10]
  [13 15 40 24]
  [39 19  7 16]]]


<div class = "alert alert-block alert-info"
    <b>35. Write a NumPy program to multiply two given arrays of same size element-by-element.</b>
</div>   

In [38]:
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])

nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])

print("Multiply said arrays of same size element-by-element: \n")
print(np.multiply(nums1, nums2)) 

Multiply said arrays of same size element-by-element: 

[[10 15  8]
 [ 3 10 25]]
