In [2]:
import numpy as np

##  1. array of 10 zeros


In [26]:
arr1 = np.zeros(10)
print(arr1)
arr2 = np.ones(10)
print(arr2)

arr3 = np.ones(10)*5
print(arr3)

arr31 = np.full(10,5)
print(arr31)

arr4 = np.arange(10,51)
print(arr4)

arr5 = np.linspace(10,50,41)
print(arr5)

arr6 = np.arange(10,51,2)
print(arr6)

arr7 = np.linspace(10,50,21)
print(arr7)

arr8 = np.arange(0,9).reshape(3,3)
print(arr8)

arr9 = np.random.randint(0,8,size=(3,3))
print(arr9)

arr10 = np.eye(3)
print(arr10)

arr11 = np.random.rand(1)
print(arr11)

arr12 = np.random.randn(25)
print(arr12)

arr13 = np.linspace(0,1,20)
print(arr13)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[5 7 4]
 [1 5 3]
 [3 1 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.84501945]
[ 0.08545086  1.07348755 -1.37317693 -1.32341331 -0.34136133 -0.74466204
 -1.51634637  0.79554413  1.09310613 -0.34673082 -0.07453251  0.48511923
  0.11191714  0.61497398  0.66349708  1.16640406 -0.18161008  0.03490244
 -1.31304541 -0.15727655  0.39503112 -0.15020656  0.98226998  0.78103962
  0.09139449]
[0.         0.05263158 0