## Basic

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

## Creating numpy array by three ways:

### 1. Transform python list
### 2. Use built-in functions
### 3. Generate random date

In [3]:
# 1. Transform python list
my_list = [1,2,3,4]
print(np.array(my_list))

[1 2 3 4]


In [19]:
# -----1D
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
#------2D
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [20]:
#------3D
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
# 2. Use built-in functions
print(np.arange(1,10))
print(np.arange(1,10,2))  # it doesn't include stop , step = how much we have to skip
print(np.linspace(1,100,5))   # it include stop , step = np.size
print(np.linspace(0,10,3))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[  1.    25.75  50.5   75.25 100.  ]
[ 0.  5. 10.]


In [14]:
#  zeros and ones array generate
print(np.zeros(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# random number array
print(np.random.rand(2))
print(np.random.rand(5,5))

print()
print(np.random.randn(2))
print(np.random.randn(5,5))

print()
print(np.random.randint(1,100))  # single random integer btn 1 to 100
print(np.random.randint(1,100,10))  # 10 random integer btn 1 to 100

print()
np.random.seed(77)    # after using seed we all over world has same value of random number
print(np.random.rand(4))

[0.67969204 0.54427582]
[[0.18784934 0.61826346 0.37412777 0.93358217 0.6481412 ]
 [0.67179118 0.93157357 0.66998809 0.23212451 0.25583435]
 [0.22499182 0.08070066 0.18400024 0.72494937 0.99893064]
 [0.14317012 0.2207215  0.27845295 0.74705776 0.98048199]
 [0.77799509 0.69514283 0.94845494 0.07784826 0.21006527]]

[1.07845754 0.59611431]
[[-0.31396856  0.09306814 -0.46312169 -0.23982402  0.43208362]
 [ 0.28188703  0.23508651 -0.12795584 -1.59018911 -1.73259801]
 [-0.94299037 -0.54852224 -3.28966079  0.40039251 -0.72124738]
 [ 0.93093701  0.14248528  0.6168811  -0.00865908  2.22928578]
 [ 1.3972282   0.14397149  1.60438932 -0.07787215 -0.70016767]]

53
[96 40 82  1 65 95 95 20 31 55]

[0.91910903 0.6421956  0.75371223 0.13931457]


In [31]:
# reshape

arr = np.arange(25)
print(arr.shape)
print(arr.reshape(5,5))

(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
arr = np.arange(0,10)
print(arr)
print(arr+arr)
print(arr-arr)
print(arr*arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
