In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
arr[1][2]

7

In [4]:
arr[1]

array([5, 6, 7])

In [5]:
arr[1,2]=10
arr

array([[ 1,  2,  3],
       [ 5,  6, 10]])

## How can you find the shape and size of a NumPy array?

In [6]:
arr.shape

(2, 3)

In [7]:
arr.size

6

## How do you apply a function to all elements of a NumPy array?

In [8]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2], [3, 4]])

# Define a function to apply (e.g., sum of elements)
sumarr = np.sum(array,axis=1)
print(sumarr)

[3 7]


In [9]:
arr = np.empty((2,2))
print(arr)

[[1.28919639e-311 1.28919639e-311]
 [1.28919639e-311 1.28919639e-311]]


In [10]:
arr.transpose()

array([[1.28919639e-311, 1.28919639e-311],
       [1.28919639e-311, 1.28919639e-311]])

In [11]:
arr1 = np.array([[1,10,3],[5,6,7]])
arr1

array([[ 1, 10,  3],
       [ 5,  6,  7]])

In [12]:
arr1[1,2]=20
print(arr1)

[[ 1 10  3]
 [ 5  6 20]]


In [15]:
arr1.sort(axis=0)
arr1

array([[ 1,  3, 10],
       [ 5,  6, 20]])

In [16]:
x2=np.array([[1,2],[3,4]])
y2=np.array([[4,5],[5,6]])
print(x2)
print(y2)
np.concatenate((x2,y2), axis=0)

[[1 2]
 [3 4]]
[[4 5]
 [5 6]]


array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])

In [32]:
x2 = np.array([[1, 2,7], [3, 4,9], [6, 7,9], [3, 4,9]])
print(x2)
result = np.split(x2, [2,3])
print(result)

[[1 2 7]
 [3 4 9]
 [6 7 9]
 [3 4 9]]
[array([[1, 2, 7],
       [3, 4, 9]]), array([[6, 7, 9]]), array([[3, 4, 9]])]
